# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
      - "main"
      - "release_*"
      - "feature/9/use_k8s_for_builds"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: k8s-opencast
    # Set permissions of the job
    permissions:
      contents: read
      packages: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: true

      - name: Build ILIAS image
        uses: docker://ghcr.io/opencast-ilias/docker-ilias-image-builder
        env:
          ILIAS_IMAGE: "srsolutions/ilias:9"
          CONTEXT: ${{ github.workspace }}
          TARGET_DIR: /var/www/html
          DESTINATION: ghcr.io/opencast-ilias/reviewapps:${{ github.sha }}
          REGISTRY: ghcr.io
          REGISTRY_USER: ${{ github.actor }}
          REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        with:
          entrypoint: /usr/local/bin/build-ilias-image
          args: --skip-push-permission-check

  deploy:
    runs-on: k8s-opencast
    needs: build
    steps:
      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Configure Kubeconfig
        uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Deploy the Helm chart
        run: >
          helm upgrade --install ilias oci://registry-1.docker.io/srsolutions/ilias
          --namespace review-test --create-namespace
          --set image.repository=ghcr.io/opencast-ilias/reviewapps
          --set image.tag=${{ github.sha }}
          --set revisionHistoryLimit=1
          --set-json args='["apache2-foreground", "-c", "StartServers 1", "-c", "MinSpareServers 1", "-c", "MaxSpareServers 2"]'
          --set persistence.size=1Gi
          --set mariadb.primary.persistence.size=1Gi
          --set mariadb.primary.extraFlags='--innodb_buffer_pool_size=33554432 --key_buffer_size=10485760'
          --set persistence.storageClass=cloudscale-volume-ssd
          --set ingress.enabled=true
          --set ingress.hostname=test.opencast.k8s.sr.solutions
          --set iliasRootPassword=review
