# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
      - "release_*"
      - "pr_*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: k8s-opencast
    # Set permissions of the job
    permissions:
      contents: read
      packages: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: true

      - name: Build ILIAS image
        uses: opencast-ilias/actions/build-ilias@main
        with:
          ilias_image: "srsolutions/ilias:9"
          destination: ghcr.io/opencast-ilias/reviewapps:${{ github.sha }}
          registry_password: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    runs-on: k8s-opencast
    needs: build
    steps:
      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Configure Kubeconfig
        uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Deploy the Helm chart
        uses: opencast-ilias/actions/deploy-ilias@main
        with:
          namespace: review-release_9
          image_repository: ghcr.io/opencast-ilias/reviewapps
          image_tag: ${{ github.sha }}
          ingress_hostname: release_9.opencast.k8s.sr.solutions
