name: Sync ILIAS

on:
  workflow_dispatch:
    inputs:
      src_namespace:
        description: Source namespace
        required: true
        default: review-release-9
      dest_namespace:
        description: Destination namespace
        required: true
        default:

jobs:
  sync:
    runs-on: k8s-opencast
    steps:
      - name: Sync ILIAS data
        uses: opencast-ilias/actions/sync-ilias@main
        with:
          src_namespace: ${{ inputs.src_namespace }}
          dest_namespace: ${{ inputs.dest_namespace }}
