name: Sync ILIAS data

on:
  workflow_dispatch:
    inputs:
      src_namespace:
        required: true
        default: release-9
      dest_namespace:
        required: true
        default:

jobs:
  sync:
    runs-on: k8s-opencast
    steps:
      - name: Configure Kubeconfig
        uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Sync ILIAS data
        uses: opencast-ilias/actions/sync-ilias@main
        with:
          src_namespace: ${{ inputs.src_namespace }}
          dest_namespace: ${{ inputs.dest_namespace }}
