name: Update ILIAS

on:
  workflow_dispatch:
    inputs:
      namespace:
        description: Namespace
        required: true
        default: review-release-9

jobs:
  update:
    runs-on: k8s-opencast
    steps:
      - name: Update ILIAS
        uses: opencast-ilias/actions/update-ilias@main
        with:
          namespace: ${{ inputs.namespace }}
